import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';

const endpoint = process.env.CDP_ENDPOINT ?? 'http://127.0.0.1:9231';
const targets = await (await fetch(`${endpoint}/json`)).json();
const target = targets.find((entry) => entry.type === 'page' && entry.url.includes('127.0.0.1:4180'));
assert.ok(target, 'Chrome must have a local hotel tab');
const socket = new WebSocket(target.webSocketDebuggerUrl);
await new Promise((resolve, reject) => {
  socket.addEventListener('open', resolve, { once: true });
  socket.addEventListener('error', reject, { once: true });
});
let id = 1;
const pending = new Map();
socket.addEventListener('message', ({ data }) => {
  const message = JSON.parse(data);
  if (!pending.has(message.id)) return;
  const entry = pending.get(message.id); pending.delete(message.id);
  message.error ? entry.reject(Error(message.error.message)) : entry.resolve(message.result);
});
const call = (method, params = {}) => new Promise((resolve, reject) => {
  const key = id++; pending.set(key, { resolve, reject }); socket.send(JSON.stringify({ id: key, method, params }));
});
const evaluate = async (expression) => {
  const result = await call('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true });
  if (result.exceptionDetails) throw Error(result.exceptionDetails.exception?.description || result.exceptionDetails.text);
  return result.result.value;
};
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

await call('Runtime.enable');
await call('Network.enable');
await call('Network.setCacheDisabled', { cacheDisabled: true });
await call('Page.navigate', { url: `http://127.0.0.1:4180/3d/editor.html?qa=${Date.now()}` });
for (let attempt = 0; attempt < 50 && !await evaluate('Boolean(window.__HOTEL_EDITOR_TEST__)'); attempt++) await delay(100);
assert.ok(await evaluate('Boolean(window.__HOTEL_EDITOR_TEST__)'), 'Hotel Builder failed to boot');
assert.ok((await evaluate('Object.keys(window.__HOTEL_EDITOR_TEST__.CATALOG).length')) >= 15);
const cameraBeforeMove = JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.cameraState)'));
await call('Input.dispatchKeyEvent', { type: 'keyDown', code: 'KeyW', key: 'w' });
await delay(300);
await call('Input.dispatchKeyEvent', { type: 'keyUp', code: 'KeyW', key: 'w' });
const cameraAfterMove = JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.cameraState)'));
assert.notDeepEqual(cameraAfterMove.target, cameraBeforeMove.target, 'W should move the camera target');
await call('Input.dispatchMouseEvent', { type: 'mouseWheel', x: 600, y: 250, deltaX: 0, deltaY: 400 });
await delay(100);
assert.ok(await evaluate('window.__HOTEL_EDITOR_TEST__.cameraState.distance') > cameraAfterMove.distance, 'Mouse wheel should zoom out');
await evaluate("document.querySelector('#reset-view').click()");
assert.deepEqual(JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.cameraState.target)')), [0,0,0]);
assert.equal(await evaluate('window.__HOTEL_EDITOR_TEST__.cameraState.distance'), 20);
const angleBeforeDrag = await evaluate('window.__HOTEL_EDITOR_TEST__.cameraState.angle');
await call('Input.dispatchMouseEvent', { type: 'mousePressed', x: 600, y: 280, button: 'right', buttons: 2, clickCount: 1 });
await call('Input.dispatchMouseEvent', { type: 'mouseMoved', x: 650, y: 280, button: 'right', buttons: 2 });
await call('Input.dispatchMouseEvent', { type: 'mouseReleased', x: 650, y: 280, button: 'right', buttons: 0, clickCount: 1 });
assert.notEqual(await evaluate('window.__HOTEL_EDITOR_TEST__.cameraState.angle'), angleBeforeDrag, 'Right-drag should rotate the view');
const targetBeforePan = JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.cameraState.target)'));
await call('Input.dispatchMouseEvent', { type: 'mousePressed', x: 600, y: 280, button: 'middle', buttons: 4, clickCount: 1 });
await call('Input.dispatchMouseEvent', { type: 'mouseMoved', x: 630, y: 300, button: 'middle', buttons: 4 });
await call('Input.dispatchMouseEvent', { type: 'mouseReleased', x: 630, y: 300, button: 'middle', buttons: 0, clickCount: 1 });
assert.notDeepEqual(JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.cameraState.target)')), targetBeforePan, 'Middle-drag should pan the view');
await evaluate("document.querySelector('#reset-view').click()");
await evaluate("[...document.querySelectorAll('#presets button')].find(button=>button.textContent==='Standard Room A').click()");
assert.equal(await evaluate('window.__HOTEL_EDITOR_TEST__.objectCount'), 11);
await evaluate(`document.querySelector('[data-floor="2"]').click()`);
assert.equal(await evaluate('window.__HOTEL_EDITOR_TEST__.floor'), 2);
await evaluate("[...document.querySelectorAll('#palette button')].find(button=>button.textContent.includes('Villain Console')).click()");
assert.equal(await evaluate('window.__HOTEL_EDITOR_TEST__.objectCount'), 12);
await evaluate("document.querySelector('#object-x').value='3.5';document.querySelector('#object-x').dispatchEvent(new Event('input'))");
await delay(350);
assert.ok(await evaluate('window.__HOTEL_EDITOR_TEST__.historyLength') >= 4, 'Edits should create visible history');
await evaluate("document.querySelector('#undo').click()");
assert.notEqual(JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.serializeLayout())')).objects.at(-1).position[0], 3.5, 'Undo should restore the previous transform');
await evaluate("document.querySelector('#redo').click()");
assert.equal(JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.serializeLayout())')).objects.at(-1).position[0], 3.5, 'Redo should restore the changed transform');
await evaluate("document.querySelector('#object-list button:last-of-type').click();document.querySelector('#object-name').value='VIP Control Console';document.querySelector('#object-name').dispatchEvent(new Event('change'))");
await evaluate("document.querySelector('#material-color').value='#e84ca5';document.querySelector('#material-color').dispatchEvent(new Event('input'))");
await delay(350);
const layout = JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.serializeLayout())'));
assert.equal(layout.version, 1);
assert.equal(layout.objects.at(-1).floor, 2);
assert.equal(layout.objects.at(-1).position[0], 3.5);
assert.equal(layout.objects.at(-1).name, 'VIP Control Console');
assert.equal(layout.objects.at(-1).material.color, '#e84ca5');
assert.equal(await evaluate("document.querySelectorAll('#object-list button').length"), 1, 'Outliner should list current-floor objects');
await evaluate("document.querySelector('#palette-search').value='Point Light';document.querySelector('#palette-search').dispatchEvent(new Event('input'))");
assert.equal(await evaluate("document.querySelectorAll('#palette button').length"), 1, 'Asset search should filter the browser');
await evaluate("document.querySelector('#palette button').click()");
assert.equal(await evaluate('window.__HOTEL_EDITOR_TEST__.objectCount'), 13);
await evaluate("document.querySelector('#light-intensity').value='7.5';document.querySelector('#light-intensity').dispatchEvent(new Event('input'))");
await delay(350);
assert.equal(JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.serializeLayout())')).objects.at(-1).light.intensity, 7.5);
assert.equal(await evaluate("document.querySelectorAll('#object-list button').length"), 2, 'Outliner should update when an asset is added');
await evaluate(`{const buttons=document.querySelectorAll('#object-list button');buttons[0].click();buttons[1].dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}));}`);
assert.equal(await evaluate('window.__HOTEL_EDITOR_TEST__.selectionCount'), 2, 'Ctrl-click should multi-select objects');
await evaluate("document.querySelector('#object-collection').value='VIP Tech';document.querySelector('#object-collection').dispatchEvent(new Event('change'))");
assert.equal(JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.serializeLayout())')).objects.filter(object=>object.editor?.collection==='VIP Tech').length, 2, 'Collections should apply to the multi-selection');
await evaluate("document.querySelector('#save-version').click()");
assert.ok(await evaluate("JSON.parse(localStorage.getItem('grand-disaster-layout-versions')).length") >= 1, 'Version snapshots should persist');
await evaluate("document.querySelector('#verify-scene').click()");
assert.ok(await evaluate("document.querySelector('#action-log').textContent.includes('Verified scene')"), 'Verification should be recorded in the action log');
await evaluate("document.querySelector('#play-test').click()");
assert.equal(await evaluate('window.__HOTEL_EDITOR_TEST__.cameraState.playMode'), true, 'Play-test should enter player-height mode');
await evaluate("document.querySelector('#play-test').click()");
assert.equal(await evaluate('window.__HOTEL_EDITOR_TEST__.cameraState.playMode'), false, 'Play-test should return to edit mode');
await evaluate(`document.querySelector('[data-floor="1"]').click()`);
await delay(250);
const image = await call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
await writeFile(new URL('../preview-editor.png', import.meta.url), Buffer.from(image.data, 'base64'));
await evaluate("window.__HOTEL_EDITOR_TEST__.loadLayout({version:1,name:'Model Showcase',objects:[]});[...document.querySelectorAll('#presets button')].find(button=>button.textContent==='New Props Showcase').click();window.__HOTEL_EDITOR_TEST__.select(null);document.querySelector('#palette-search').value='';document.querySelector('#palette-search').dispatchEvent(new Event('input'));document.querySelector('#reset-view').click()");
assert.equal(await evaluate('window.__HOTEL_EDITOR_TEST__.objectCount'), 14, 'Model showcase should add a floor, display wall, and twelve new models');
const showcaseTypes = JSON.parse(await evaluate('JSON.stringify(window.__HOTEL_EDITOR_TEST__.serializeLayout().objects.map(object=>object.type))'));
for (const type of ['suitcase','wardrobe','minibar','roomService','housekeeping','velvetRope','roomPlaque','securityCamera','weatherMachine','portalMirror','chandelier','wallSconce']) assert.ok(showcaseTypes.includes(type), `${type} missing from showcase`);
await delay(250);
const showcaseImage = await call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
await writeFile(new URL('../preview-model-batch.png', import.meta.url), Buffer.from(showcaseImage.data, 'base64'));
await evaluate("document.querySelector('#view-right').click();document.querySelector('#view-right').click()");
await delay(150);
const showcaseAltImage = await call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
await writeFile(new URL('../preview-model-batch-alt.png', import.meta.url), Buffer.from(showcaseAltImage.data, 'base64'));
socket.close();
console.log('Hotel Builder browser QA: PASS — camera, asset search, outliner, transforms, materials, history, versions, verification, play-test, model showcase, serialization, and render.');
