import * as THREE from './vendor/three.module.js';
import { VILLAIN_ROSTER } from './characters/villain-roster.js';
import { createVillainCharacter, inspectVillainCharacter, updateVillainCharacter } from './characters/villain-builder.js';

const canvas=document.getElementById('roster-canvas');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x100b17);scene.fog=new THREE.Fog(0x100b17,24,54);scene.add(new THREE.HemisphereLight(0xd8dcff,0x321b42,3.1));const sun=new THREE.DirectionalLight(0xffd3ae,2.7);sun.position.set(9,18,11);scene.add(sun);
const camera=new THREE.PerspectiveCamera(48,1,.1,100);const target=new THREE.Vector3(0,1.15,0);let yaw=0,distance=23,elevation=.48;const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let drag=null;
const lineup=new THREE.Group();scene.add(lineup);const entries=[];
const pedestalMat=new THREE.MeshStandardMaterial({color:0x25172e,metalness:.45,roughness:.35});
for(let index=0;index<VILLAIN_ROSTER.length;index++){
  const data=VILLAIN_ROSTER[index],group=createVillainCharacter(data);const column=index%10,row=Math.floor(index/10);group.position.set((column-4.5)*2.25,0,(row-1)*3.15);group.rotation.y=Math.PI;group.userData.baseY=0;group.userData.phase=index*.61;group.userData.rosterIndex=index;
  group.traverse((node)=>{node.userData.rosterRoot=group;});lineup.add(group);
  const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(.72,.82,.12,12),pedestalMat);pedestal.position.set(group.position.x,.02,group.position.z);pedestal.userData.rosterIndex=index;lineup.add(pedestal);
  entries.push({data,group,report:inspectVillainCharacter(group)});
}
const ground=new THREE.Mesh(new THREE.PlaneGeometry(34,16),new THREE.MeshStandardMaterial({color:0x17101f,roughness:.78,metalness:.08}));ground.rotation.x=-Math.PI/2;ground.position.y=-.05;scene.add(ground);const grid=new THREE.GridHelper(34,34,0xd59a4e,0x402c49);grid.position.y=-.04;scene.add(grid);
function updateCamera(){camera.position.set(target.x+Math.sin(yaw)*distance,target.y+distance*elevation,target.z+Math.cos(yaw)*distance);camera.lookAt(target);}
function resetCamera(){yaw=0;distance=23;elevation=.48;target.set(0,1.15,0);updateCamera();}
function visibleEntries(){return entries.filter((entry)=>entry.group.visible);}
function showBatch(batch){entries.forEach((entry,index)=>entry.group.visible=batch==='all'||Math.floor(index/5)===Number(batch));lineup.children.filter((child)=>child.userData.rosterIndex!==undefined&&!child.userData.rosterRoot).forEach((pedestal)=>{pedestal.visible=batch==='all'||Math.floor(pedestal.userData.rosterIndex/5)===Number(batch);});document.querySelectorAll('[data-batch]').forEach((button)=>button.classList.toggle('active',button.dataset.batch===String(batch)));const visible=visibleEntries(),reports=visible.map((entry)=>entry.report);document.getElementById('triangle-total').textContent=Math.round(reports.reduce((sum,report)=>sum+report.triangles,0)).toLocaleString();if(batch!=='all'&&visible.length){target.set(visible.reduce((sum,entry)=>sum+entry.group.position.x,0)/visible.length,1.1,visible.reduce((sum,entry)=>sum+entry.group.position.z,0)/visible.length);distance=12;yaw=0;elevation=.34;updateCamera();}else if(batch==='all')resetCamera();}
function selectEntry(entry){const data=entry.data,report=entry.report;document.getElementById('selected-card').innerHTML=`<small>ROOM ${data.room} · ${data.power.toUpperCase()}</small><h2>${data.name}</h2><div class="trait"><b>Personality</b><span>${data.personality}</span></div><div class="trait"><b>Body</b><span>${data.bodyType}</span></div><div class="trait"><b>Expression</b><span>${data.expression}</span></div><div class="trait"><b>Outfit</b><span>${data.outfit}</span></div><div class="trait"><b>Accessories</b><span>${data.accessories.join(' · ')}</span></div><div class="trait"><b>Signature prop</b><span>${data.signatureProp}</span></div><div class="trait"><b>Request item</b><span>${data.item}</span></div><div class="trait"><b>Room theme</b><span>${data.roomTheme}</span></div><div class="trait"><b>Geometry</b><span>${report.meshes} meshes · ${report.triangles.toLocaleString()} triangles · ${report.dimensions.join(' × ')} m</span></div><p class="request">“${data.request}”</p>`;target.set(entry.group.position.x,1.05,entry.group.position.z);distance=6;updateCamera();}
document.querySelectorAll('[data-batch]').forEach((button)=>button.onclick=()=>showBatch(button.dataset.batch));document.getElementById('reset-camera').onclick=resetCamera;
canvas.addEventListener('contextmenu',(event)=>event.preventDefault());canvas.addEventListener('pointerdown',(event)=>{drag={x:event.clientX,y:event.clientY,lastX:event.clientX,lastY:event.clientY,button:event.button,moved:false};canvas.setPointerCapture?.(event.pointerId);});canvas.addEventListener('pointermove',(event)=>{if(!drag)return;const dx=event.clientX-drag.lastX,dy=event.clientY-drag.lastY;if(Math.hypot(event.clientX-drag.x,event.clientY-drag.y)>4)drag.moved=true;if(drag.button===2){yaw-=dx*.009;elevation=THREE.MathUtils.clamp(elevation+dy*.007,.12,1.25);updateCamera();}else if(drag.button===1){const scale=distance*.0025;target.x-=dx*scale;target.z-=dy*scale;updateCamera();}drag.lastX=event.clientX;drag.lastY=event.clientY;});canvas.addEventListener('pointerup',(event)=>{if(!drag)return;const click=!drag.moved&&drag.button===0;drag=null;if(!click)return;const rect=canvas.getBoundingClientRect();pointer.set(((event.clientX-rect.left)/rect.width)*2-1,-((event.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(entries.filter((entry)=>entry.group.visible).map((entry)=>entry.group),true)[0];const root=hit?.object.userData.rosterRoot;if(root)selectEntry(entries[root.userData.rosterIndex]);});canvas.addEventListener('wheel',(event)=>{event.preventDefault();distance=THREE.MathUtils.clamp(distance*Math.exp(event.deltaY*.0012),4,40);updateCamera();},{passive:false});
function resize(){const width=canvas.clientWidth,height=canvas.clientHeight;if(canvas.width!==Math.floor(width*renderer.getPixelRatio())||canvas.height!==Math.floor(height*renderer.getPixelRatio())){renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();}}
const dummyPlayer={x:999,z:999};function frame(now){resize();for(const entry of visibleEntries())updateVillainCharacter(entry,dummyPlayer,now/1000);renderer.render(scene,camera);requestAnimationFrame(frame);}resetCamera();showBatch('all');requestAnimationFrame(frame);
window.__VILLAIN_ROSTER_TEST__={entries,reports:entries.map((entry)=>entry.report),showBatch,selectEntry,setCamera:(nextYaw,nextElevation,nextDistance)=>{yaw=nextYaw;elevation=nextElevation;distance=nextDistance;updateCamera();},get visibleCount(){return visibleEntries().length;}};
